name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Generate Database
      run: | 
        dotnet restore src/UserPermissions.API
        dotnet tool install --global dotnet-ef
        dotnet ef database update src/UserPermissions.API
    - name: Build with dotnet
      run: dotnet build ./src/UserPermissions.API/UserPermissions.API.csproj --configuration Release
    # - name: Tests with dotnet
    #   run: dotnet test ./src/WP.WebAPI.Tests/WP.WebAPI.Tests.csproj
