#
# GitHub Actions shared solution
#
name: Publish Dto Package to Nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build, Pack, & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      # Publish
      - name: Publish if Version Changed
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/UserPermissions.Dto/UserPermissions.Dto.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: Core
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: <Version>(.*)<\/Version>
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true


#
# Personally written solution. This does not check for version updates.
#

# name: Publish DTOs

# on: [push]

# # on:
# #   push:
# #     branches:
# #       - master
# #   pull_request:
# #     types: [closed]
# #     branches:
# #       - master

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       # env:
#       #   NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  

#     - uses: actions/checkout@v1
#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 3.1.102

#     # - name: Publish NuGet
#     #   uses: brandedoutcast/publish-nuget@v2.5.2

#     - name: Build Package
#       working-directory: src/UserPermissions.Dto
#       run: dotnet pack -o nuget
#     - name: Publish Package
#       working-directory: src/UserPermissions.Dto
#       run: dotnet nuget push nuget/*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
